CREATE TABLE Occurrence (
  idOccurrence INT UNSIGNED NOT NULL,
  code INT UNSIGNED NOT NULL,
  type VARCHAR(20) NOT NULL,
  title VARCHAR(70) NOT NULL,
  latitude DOUBLE NOT NULL,
  longitude DOUBLE NOT NULL,
  date_time DATETIME NOT NULL,
  description VARCHAR(350) NULL,
  object_1 TINYINT(1) NULL,
  object_2 TINYINT(1) NULL,
  object_3 TINYINT(1) NULL,
  object_4 TINYINT(1) NULL,
  object_5 TINYINT(1) NULL,
  object_6 TINYINT(1) NULL,
  object_7 TINYINT(1) NULL,
  object_8 TINYINT(1) NULL,
  object_9 TINYINT(1) NULL,
  object_10 TINYINT(1) NULL,
  object_11 TINYINT(1) NULL,
  object_12 TINYINT(1) NULL,
  object_13 TINYINT(1) NULL,
  object_14 TINYINT(1) NULL,
  object_15 TINYINT(1) NULL,
  object_16 TINYINT(1) NULL,
  object_17 TINYINT(1) NULL,
  object_18 TINYINT(1) NULL,
  object_19 TINYINT(1) NULL,
  PRIMARY KEY (`idOccurrence`))
